name: Flutter CI

on:
  push:
    branches: [ "main", "dev" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'

      # FIX LATER !!
      # keystore base64 is corrupted
      # release-key.keystore is empty

      # Recreate keystore from Base64 secret
      - name: Restore Android keystore
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/release-key.keystore

      # Create key.properties
      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=./release-key.keystore
          EOF

      # Print SHA1 and SHA256 fingerprints
      # - name: Print SHA1 and SHA256 fingerprints
      #   run: |
      #     keytool -list -v -keystore android/app/release-key.keystore \
      #       -alias "$ANDROID_KEY_ALIAS" \
      #       -storepass "$ANDROID_KEYSTORE_PASSWORD" \
      #       -keypass "$ANDROID_KEY_PASSWORD"

      # Setup Java & Gradle
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Generate google-services.json dari secrets
      - name: Create google-services.json
        run: |
          if [ -n "${{ secrets.GOOGLE_SERVICES_JSON }}" ]; then
            echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json
            echo "google-services.json created."
          else
            echo "No GOOGLE_SERVICES_JSON secret found, skipping..."
          fi

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Jalankan test
      # - name: Run tests
      #   run: flutter test

      # Build APK release
      - name: Build release APK
        run: flutter build apk --release

      # Simpan hasil build (artifact)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      # Upload ke firebase app distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
